### ISSUE TITLE
scripts: junit2issue.py script is failing while parsing the xml file

### ISSUE THREAD

**Issue by yerabolu** [zephyrproject-rtos/test_results#460]
junit2issue.py script is failing while parsing the .XML file. Installed the python dependencies and below is the command used & environment details: 

python3 ./junit2issue.py -v zephyr-v2.6.0-983-g2486b4509873 -i mec15xxevb_assy6853.xml -r https://github.com/yerabolu/zephyr

**Error:** 
```
./junit2issue.py:27: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[junit2issue.py:180] MainThread Namespace(auto_report=False, pfile='mec15xxevb_assy6853.xml', report_errors=False, report_repo='https://github.com/yerabolu/zephyr', vfolder='zephyr-v2.6.0-983-g2486b4509873')
[junit2issue.py:52] MainThread check result with <class 'junitparser.junitparser.Failure'>:
name = mec15xxevb_assy6853
time = 1969.338274
tests = 9933
failures = 2
errors = 0
skipped = 8815
version : zephyr-v2.6.0-983-g2486b4509873
Traceback (most recent call last):
  File "./junit2issue.py", line 189, in <module>
    reports = parser_testsuites_for_result(_xml, Failure)
  File "./junit2issue.py", line 75, in parser_testsuites_for_result
    for res in my_case.result:
TypeError: 'NoneType' object is not iterable
```
**Environment:** 
OS: Fedora 29

**Comment by yerabolu** [comment]
Issue was due to junitparser and was able to resolve it once it is upgraded to the latest version.
